name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        go: [ 1.23.x ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test --cpu 1,4 -race -coverprofile coverage.out -covermode atomic ./...

      - name: 'Coverage'
        shell: 'bash'
        working-directory: '${{ inputs.directory }}'
        run: |-
          OUTPUT="$(go tool cover -func=./coverage.out)"
          TOTAL="$(echo $OUTPUT | awk 'END{print $NF}')"
          tee -a $GITHUB_STEP_SUMMARY > /dev/null <<EOF
            ## Coverage: ${TOTAL}

            \`\`\`text
            ${OUTPUT}
            \`\`\`
          EOF
